// Importa tipos do Next.js para metadados da página
import type { Metadata } from "next";

// Importa as novas fontes do Next.js 15 (Geist)
import { Geist, Geist_Mono } from "next/font/google";

// Importa estilos globais CSS
import "./globals.css";

// Configura a fonte Geist Sans (fonte principal)
const geistSans = Geist({
  variable: "--font-geist-sans", // Variável CSS para usar a fonte
  subsets: ["latin"], // Subconjunto de caracteres (latim)
});

// Configura a fonte Geist Mono (para código/monospace)
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // Variável CSS para usar a fonte
  subsets: ["latin"], // Subconjunto de caracteres (latim)
});

// Metadados da página (SEO)
export const metadata: Metadata = {
  title: "Create Next App", // Título da página
  description: "Generated by create next app", // Descrição
};

// Componente de layout principal - envolve toda a aplicação
export default function RootLayout({
  children, // Conteúdo das páginas filhas
}: Readonly<{
  // Readonly = somente leitura (boa prática do TypeScript)
  children: React.ReactNode; // Pode ser qualquer elemento React
}>) {
  // Retorna JSX do layout
  return (
    // Elemento HTML raiz
    <html lang="en">
      {/* Corpo da página com as fontes configuradas */}
      <body
        // Aplica as variáveis CSS das fontes + classe antialiased para suavizar fontes
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Conteúdo das páginas filhas será injetado aqui */}
        {children}
      </body>
    </html>
  );
}
